export { Hero } from './Hero';
export { About } from './About';
export { Experience } from './Experience';
export { Skills } from './Skills';
export { Services } from './Services';
export { Projects } from './Projects';
export { Achievements } from './Achievements';
export { Testimonials } from './Testimonials';
export { Contact } from './Contact';
