export const portfolioData = {
  personal: {
    name: 'Shannice Wangui Gichia',
    title: 'Executive Assistant | Virtual Assistant | Operations Coordinator',
    location: 'Nairobi, Kenya',
    email: 'hello@shannice.dev',
    phone: '+254 (0) 700 000 000',
    summary: `Highly organized Executive Assistant with experience supporting executives, entrepreneurs, nonprofits, and remote teams. Skilled in executive scheduling, calendar management, CRM systems, administration, research, Canva, webinar coordination, project management, and communication. Passionate about technology, AI, and continuous learning.`,
    avatar: '/avatar.jpg',
    cv: '/resume.pdf',
  },
  experience: [
    {
      id: 1,
      title: 'Executive Coordinator',
      company: 'Mbele Leadership Foundation',
      period: '2022 - Present',
      description: `Managed executive operations and scheduling for organizational leadership. Coordinated high-level meetings, events, and communications. Streamlined internal processes using Google Workspace and CRM systems.`,
      achievements: [
        'Reduced meeting setup time by 40% through automation',
        'Coordinated 100+ executive meetings annually',
        'Improved communication efficiency by 35%',
      ],
      color: '#8A5CF6',
      icon: '🎯',
    },
    {
      id: 2,
      title: 'Executive Assistant to the President',
      company: 'Mbele Leadership Foundation',
      period: '2021 - 2022',
      description: `Provided comprehensive executive support to the President. Managed calendars, correspondence, travel arrangements, and special projects. Coordinated board meetings and organizational initiatives.`,
      achievements: [
        'Organized quarterly board meetings',
        'Managed $500K+ event coordination',
        'Achieved 99% scheduling accuracy',
      ],
      color: '#B78BFA',
      icon: '👔',
    },
    {
      id: 3,
      title: 'Administrative Assistant',
      company: "The College Counselor's Coach",
      period: '2020 - 2021',
      description: `Provided administrative support for coaching and mentorship organization. Managed databases, scheduling, client communications, and marketing materials.`,
      achievements: [
        'Maintained 500+ client database',
        'Processed 200+ monthly admin tasks',
        'Created 50+ marketing materials',
      ],
      color: '#E9D9FF',
      icon: '📋',
    },
    {
      id: 4,
      title: 'Executive Virtual Assistant',
      company: 'Podcastify',
      period: '2019 - 2020',
      description: `Supported podcast production and management. Coordinated guest scheduling, managed social media, handled podcast editing coordination, and administrative tasks.`,
      achievements: [
        'Coordinated 80+ podcast episodes',
        'Grew social media followers by 150%',
        'Managed podcast release schedule',
      ],
      color: '#5D2A7F',
      icon: '🎙️',
    },
    {
      id: 5,
      title: 'Data Extractor',
      company: 'CloudFactory',
      period: '2018 - 2019',
      description: `Extracted, organized, and validated data from various sources. Ensured data accuracy and consistency for business intelligence purposes.`,
      achievements: [
        'Processed 10,000+ data points monthly',
        'Achieved 99.8% accuracy rate',
        'Improved data processing by 25%',
      ],
      color: '#280B39',
      icon: '📊',
    },
  ],
  skills: [
    { name: 'Executive Support', category: 'Core', level: 95, icon: '🎯' },
    { name: 'Virtual Assistance', category: 'Core', level: 90, icon: '💻' },
    { name: 'Administration', category: 'Core', level: 88, icon: '📋' },
    { name: 'Research', category: 'Core', level: 85, icon: '🔍' },
    { name: 'Communication', category: 'Soft Skills', level: 92, icon: '💬' },
    { name: 'Leadership', category: 'Soft Skills', level: 85, icon: '👥' },
    { name: 'Project Coordination', category: 'Soft Skills', level: 88, icon: '📊' },
    { name: 'Google Workspace', category: 'Technology', level: 95, icon: '🔷' },
    { name: 'Microsoft Office', category: 'Technology', level: 90, icon: '📱' },
    { name: 'Canva', category: 'Technology', level: 85, icon: '🎨' },
    { name: 'CRM Systems', category: 'Technology', level: 88, icon: '📈' },
    { name: 'Mailchimp', category: 'Technology', level: 82, icon: '📧' },
    { name: 'Zoom', category: 'Technology', level: 90, icon: '🎥' },
    { name: 'Calendar Management', category: 'Specialized', level: 95, icon: '📅' },
    { name: 'Webinar Management', category: 'Specialized', level: 87, icon: '🌐' },
  ],
  services: [
    {
      id: 1,
      title: 'Executive Assistance',
      description: 'Comprehensive support for busy executives including scheduling, meeting coordination, travel management, and communication.',
      icon: '👔',
      features: [
        'Calendar Management',
        'Meeting Coordination',
        'Travel Planning',
        'Correspondence Management',
        'Executive Reporting',
      ],
    },
    {
      id: 2,
      title: 'Virtual Assistance',
      description: 'Remote administrative support covering general administrative tasks, email management, and organizational support.',
      icon: '💻',
      features: [
        'Email Management',
        'Administrative Tasks',
        'Data Entry',
        'File Organization',
        'Phone Support',
      ],
    },
    {
      id: 3,
      title: 'Research',
      description: 'In-depth market research, competitive analysis, and data gathering for informed decision-making.',
      icon: '🔍',
      features: [
        'Market Research',
        'Competitive Analysis',
        'Data Compilation',
        'Report Generation',
        'Industry Analysis',
      ],
    },
    {
      id: 4,
      title: 'Project Coordination',
      description: 'End-to-end project management and coordination ensuring timely delivery and stakeholder satisfaction.',
      icon: '📊',
      features: [
        'Project Planning',
        'Timeline Management',
        'Stakeholder Coordination',
        'Progress Tracking',
        'Deliverable Management',
      ],
    },
    {
      id: 5,
      title: 'Administration',
      description: 'Professional administrative services including database management, documentation, and compliance support.',
      icon: '📋',
      features: [
        'Database Management',
        'Documentation',
        'Records Management',
        'Compliance Support',
        'Office Coordination',
      ],
    },
    {
      id: 6,
      title: 'Social Media Support',
      description: 'Social media management and content support to enhance online presence and engagement.',
      icon: '📱',
      features: [
        'Content Scheduling',
        'Social Media Management',
        'Content Creation',
        'Community Engagement',
        'Analytics Tracking',
      ],
    },
  ],
  projects: [
    {
      id: 1,
      title: 'Executive Coordination Platform',
      description: 'Developed and implemented an integrated scheduling and communication system for executive teams.',
      image: '/projects/executive-coordination.jpg',
      category: 'Executive Support',
      technologies: ['Google Workspace', 'Asana', 'Slack'],
      impact: 'Improved coordination efficiency by 40%',
      date: '2023',
    },
    {
      id: 2,
      title: 'Leadership Academy Support',
      description: 'Managed end-to-end coordination for leadership development programs and training initiatives.',
      image: '/projects/leadership-academy.jpg',
      category: 'Project Coordination',
      technologies: ['Zoom', 'Google Forms', 'Canva'],
      impact: 'Successfully coordinated 250+ participants',
      date: '2023',
    },
    {
      id: 3,
      title: 'Podcast Support System',
      description: 'Created a comprehensive system for podcast production, guest coordination, and content management.',
      image: '/projects/podcast-support.jpg',
      category: 'Podcast Support',
      technologies: ['Airtable', 'Zapier', 'Google Sheets'],
      impact: 'Managed 80+ episodes with 99% on-time delivery',
      date: '2022',
    },
    {
      id: 4,
      title: 'Webinar Management System',
      description: 'Designed and implemented a complete webinar management workflow with registration and follow-up automation.',
      image: '/projects/webinar-management.jpg',
      category: 'Webinar Management',
      technologies: ['Zoom', 'Mailchimp', 'Zapier'],
      impact: 'Handled 30+ webinars with 85% attendance rate',
      date: '2022',
    },
    {
      id: 5,
      title: 'CRM Implementation',
      description: 'Implemented and customized a CRM system for improved client management and relationship tracking.',
      image: '/projects/crm-implementation.jpg',
      category: 'CRM Management',
      technologies: ['Pipedrive', 'Google Sheets', 'Zapier'],
      impact: 'Increased client retention by 35%',
      date: '2023',
    },
    {
      id: 6,
      title: 'Administrative Automation',
      description: 'Automated repetitive administrative tasks saving 15+ hours per week through workflow optimization.',
      image: '/projects/automation.jpg',
      category: 'Administrative Support',
      technologies: ['Zapier', 'Google Workspace', 'Make.com'],
      impact: 'Achieved 40% reduction in manual work',
      date: '2023',
    },
  ],
  achievements: [
    {
      stat: '5+',
      label: 'Years Experience',
      description: 'Supporting executives and leading teams',
    },
    {
      stat: '100+',
      label: 'Meetings Coordinated',
      description: 'High-level executive meetings annually',
    },
    {
      stat: '1000+',
      label: 'Hours Saved',
      description: 'Through automation and optimization',
    },
    {
      stat: '50+',
      label: 'Marketing Materials',
      description: 'Created using Canva & design tools',
    },
  ],
  testimonials: [
    {
      name: 'Dr. Sarah Johnson',
      title: 'CEO, Tech Innovations Inc.',
      content:
        'Shannice transformed our executive operations. Her attention to detail and proactive approach increased our team productivity by 40%.',
      image: '/testimonials/sarah.jpg',
      rating: 5,
    },
    {
      name: 'Michael Chen',
      title: 'Founder, Growth Academy',
      content:
        'Working with Shannice has been a game-changer. She brings professionalism, reliability, and exceptional organizational skills.',
      image: '/testimonials/michael.jpg',
      rating: 5,
    },
    {
      name: 'Amanda Williams',
      title: 'Executive Director, nonprofit',
      content:
        'Shannice is exceptional at managing complex schedules and coordinating teams. Highly recommend her services.',
      image: '/testimonials/amanda.jpg',
      rating: 5,
    },
    {
      name: 'David Martinez',
      title: 'Entrepreneur & Consultant',
      content:
        'The level of support and dedication Shannice brings to her work is unmatched. She is a true professional.',
      image: '/testimonials/david.jpg',
      rating: 5,
    },
  ],
  education: [
    {
      institution: 'ALX Virtual Assistant Program',
      field: 'Virtual Assistance & Digital Skills',
      year: '2023',
    },
    {
      institution: 'Fata School',
      field: 'Web Development & Technology',
      year: '2022',
      courses: ['JavaScript', 'CSS', 'Python'],
    },
  ],
  languages: ['English', 'Kiswahili'],
  interests: ['Technology', 'AI', 'Travel', 'Networking', 'Community Service'],
  social: {
    linkedin: 'https://linkedin.com/in/shannice-gichia',
    twitter: 'https://twitter.com/shannicegichia',
    github: 'https://github.com/shannicegichia',
    email: 'hello@shannice.dev',
  },
};
